Untested changes to allow use of a proxy server
willvincent/feeds pull request #41
Opened 2018-02-02 07:08 UTC by peeto

Requires testing before merging

2018-02-05 16:57 UTC, willvincent requested changes
I think the change to the configure method is still somewhat limiting. Rather than specfically defining a few additional options for proxy, instead it would be more flexible to expose an array that allows for defining _any_ curl option value(s).

Otherwise the next time someone comes up with another _thing_ to override there yet another round of changes and another release become necessary.

This current approach will ultimately make that configure() code is going to get much more complicated than it needs to be...

I think this can be improved, and it'll _never_ be merged with that composer.json change.

2018-02-05 16:57 UTC, willvincent commented on composer.json
> +    "name": "peeto/feeds",
This is preventing a merge of this PR.

2018-02-05 23:35 UTC, peeto commented
@willvincent,

The curloptions array had occurred to me. So I'll do that if we're in
agreement. The composer.json change was made purely so it could be tested
and will definitely be reverted.

On 6 Feb. 2018 03:57, "Will Vincent" <notifications@github.com> wrote:

> *@willvincent* requested changes on this pull request.
>
> I think the change to the configure method is still somewhat limiting.
> Rather than specfically defining a few additional options for proxy,
> instead it would be more flexible to expose an array that allows for
> defining *any* curl option value(s).
>
> Otherwise the next time someone comes up with another *thing* to override
> there yet another round of changes and another release become necessary.
>
> That configure() code is going to get much more complicated than it needs
> to be.
>
> I think this can be improved, and it'll *never* be merged with that
> composer.json change.
> ------------------------------
>
> In composer.json
> <https://github.com/willvincent/feeds/pull/41#discussion_r166034934>:
>
> > @@ -1,5 +1,5 @@
>  {
> -    "name": "willvincent/feeds",
> +    "name": "peeto/feeds",
>
> This is preventing a merge of this PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/willvincent/feeds/pull/41#pullrequestreview-94061076>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMOupgs3I0MRbYJUK4yidiQ-AX_mhsElks5tRzLmgaJpZM4R2xEO>
> .
>

2018-02-08 03:49 UTC, peeto commented
The requested changes have been made. #40 has another request for a similar change to make() so based on the conversation here an $options parameter has been added. Please review changes but don't pull until #40 is resolved.

2018-02-08 04:28 UTC, peeto commented
The latest comments in #40 suggest all this could have been avoided by using $feed->set_curl_options()

To mitigate wasting my time I've added the ability to change the strip tags and strip attributes in make().

So to sum up #41 contains the ability to set in the configuration CURL options (eg for proxy). It also contains a change to make() to allow the strip tags, strip attributes, and CURL options to be changed from their default (config) for an individual feed. The manner in which the changes to make() have been made allow for similar requests in the future to be made without further changes to the method signature.

2018-02-08 04:34 UTC, willvincent commented
Looks good to me. Thanks :)

2018-02-08 04:34 UTC, willvincent approved these changes

2018-02-08 04:35 UTC, merged